### PR TITLE
Fix dependencies

### LINKED ISSUE #17: New packages are not being pushed after version 3.1.0
Issue:
New packages are not being pushed after version 3.1.0
Did sanity by adding bot-rerun label it seems that test is failing for new PRs and older were never merged.
Latest PR from the bot: https://github.com/conda-forge/gspread-feedstock/pull/16

Below are the dependencies that are needed to run the tests:
    - python
    - requests >=2.2.1
    - google-auth>=1.12.0
    - google-auth-oauthlib>=0.4.1

We need to:
1. Merge older PRs and push left out versions
2. Add missing dependencies

### PR DESCRIPTION
**Pull request by akashvyom**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] Ensured the license file is being packaged.

closes #17 

Changes in this PR:
Added missing required dependencies
Rerendered the files and checked in

### CODE REVIEW

**Comment by akashvyom** [comment]
@conda-forge-admin, please rerender

**Comment by akashvyom** [comment]
@beckermr can you please have a look at this

**Comment by beckermr** [comment]
Please add yourself as a maintainer and then we can merge.

cc @conda-forge/gspread

**Comment by beckermr** [comment]
@conda-forge-admin rerender for good measure

**Comment by akashvyom** [comment]
@beckermr have added me and @burnash the repo owner of gspread as maintainers

**Comment by hadim** [comment]
@conda-forge-admin please rerender

**Comment by akashvyom** [comment]
@beckermr @hadim if this looks good can we merge?

**Comment by beckermr** [comment]
@burnash needs to confirm they are ok maintaining the repo

**Comment by burnash** [comment]
@beckermr Confirm. Thank you very much.

**Pull request merged**
